apiVersion: krane.petomalina.com/v1alpha1
kind: Canary
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  target: {{ include "chart.fullname" . }}-target
  testPhase:
    image: "ubuntu"
    cmd:
      - /bin/bash
      - "-c"
      - "apt-get update -y && apt-get install curl -y && echo $KRANE_TARGET && curl $KRANE_TARGET"
  analysisPhase:
    image: "ubuntu"
    cmd: [sleep, "10"]